name: 'Download Prior Artifact'
description: 'Download an artifact from any prior workflow run of a given repository'
author: 'Alex Tompkins'
branding:
  icon: download-cloud
  color: purple
inputs:
  name:
    required: true
    description: 'Artifact name'
  path:
    required: true
    description: 'Destination path'
  repo:
    required: false
    description: 'Repository to search'
    default: ${{ github.repository }}
  commitHash:
    required: false
    description: 'Filter to Artifacts tied to a commit, and can be a partial hash'
runs:
  using: 'node16'
  main: 'dist/index.js'
